# Generated by Django 3.2.25 on 2024-11-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasinventario', '0004_auto_20241108_0346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='jefeBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=12)),
            ],
        ),
    ]
