# Generated by Django 3.2.25 on 2024-11-12 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventasinventario', '0007_administrador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='rol',
            field=models.CharField(max_length=13, verbose_name='Rol administrador/jefe de bodega'),
        ),
    ]
